### ISSUE TITLE
targetSdk 改成34，获取照片信息奔溃

### ISSUE THREAD

**Issue by ByteRax** [Android5730/DataCapture#1]
问题：

`
 FATAL EXCEPTION: main
                                                                Process: com.itaem.datacapture, PID: 13090
                                                                java.lang.IllegalArgumentException: When targetSdkVersion >= 33 should use android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_AUDIO instead of android.permission.READ_EXTERNAL_STORAGE
                                                                	at com.hjq.permissions.PermissionChecker.checkStoragePermission(PermissionChecker.java:172)
                                                                	at com.hjq.permissions.XXPermissions.request(XXPermissions.java:174)
                                                                	at com.itaem.datacapture.MainActivity.requestPermission(MainActivity.java:241)
                                                                	at com.itaem.datacapture.MainActivity.access$000(MainActivity.java:24)
                                                                	at com.itaem.datacapture.MainActivity$11.onClick(MainActivity.java:143)
                                                                	at android.view.View.performClick(View.java:7652)
                                                                	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
                                                                	at android.view.View.performClickInternal(View.java:7629)
                                                                	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                	at android.view.View$PerformClick.run(View.java:29895)
                                                                	at android.os.Handler.handleCallback(Handler.java:942)
                                                                	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                	at android.os.Looper.loopOnce(Looper.java:223)
                                                                	at android.os.Looper.loop(Looper.java:324)
                                                                	at android.app.ActivityThread.main(ActivityThread.java:8574)
                                                                	at java.lang.reflect.Method.invoke(Native Method)
                                                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
`

期望适配Android 14

**Comment by Android5730** [comment]
已经修复了，适配安卓14的图片获取，手机没有安卓14版本的，找了虚拟机试了下，没什么问题。欢迎提出更多问题
